# Generated by Django 5.0.7 on 2024-07-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutme',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='intro',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='resume_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutme',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
