# Generated by Django 5.0.7 on 2024-07-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aboutme_address_aboutme_age_aboutme_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='proficiency',
        ),
        migrations.AddField(
            model_name='skill',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
